services:
  - type: pserv
    name: auth-service
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: auth-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: auth-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: auth-db
          property: password
      - key: PORT
        value: "10000"
      - key: SERVER_PORT
        value: "10000"
      - key: APPLICATION_SECURITY_JWT_SECRET_KEY
        generateValue: true
      - key: APPLICATION_SECURITY_JWT_EXPIRATION
        value: "86400000"

databases:
  - name: auth-db
    databaseName: authservice
    user: authuser
    plan: starter