package com.goldatech.collectionsservice.web.dto.request;

import java.math.BigDecimal;

/**
 * Data Transfer Object (DTO) for making 'makePayment' requests to the external payment API.
 * This precisely mirrors the request structure expected by your third-party payment provider.
 *
 * @param reference A unique reference for idempotency, generated by our service.
 * @param amount The amount to collect.
 * @param currency The currency of the transaction (e.g., "GHS").
 * @param userId The user ID (from our system's perspective).
 * @param paymentChannel The payment channel (e.g., "USSD").
 * @param provider The payment provider (e.g., "MTN").
 * @param merchantName The merchant name.
 * @param callbackUrl The URL where the external API should send status updates to our service.
 */
public record ExternalInitiatePaymentRequest(
        String reference,
        BigDecimal amount,
        String currency,
        String userId,
        String paymentChannel,
        String provider,
        String merchantName,
        String callbackUrl
) {}